
---------------------04. JOIN---------------------

---------------------07. 서브쿼리---------------------
-- 1. 부서코드가 노옹철 사원과 같은 소속의 직원의 이름, 부서코드 조회
SELECT EMP_NAME, DEPT_CODE
FROM EMPLOYEE
WHERE DEPT_CODE = (
	SELECT DEPT_CODE
	FROM EMPLOYEE
	WHERE EMP_NAME = '노옹철'
);

-- 2. 전 직원의 평균 급여보다 많은 급여를 받고 있는 직원의 사번, 이름, 직급코드, 급여 조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > (
	SELECT AVG(SALARY)
	FROM EMPLOYEE
);
-- 3. 전 직원의 급여 평균보다 초과하여 급여를 받는 직원의 이름, 직급명, 부서명, 급여를 직급 순으로 정렬하여 조회
SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
WHERE SALARY > (
	SELECT AVG(SALARY)
	FROM EMPLOYEE
)
ORDER BY J.JOB_CODE;

-- 4. 가장 적은 급여를 받는 직원의 사번, 이름, 직급명, 부서코드, 급여, 입사일 조회
SELECT MIN(SALARY)
FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, JOB_NAME, DEPT_CODE, SALARY, HIRE_DATE
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE SALARY = (
	SELECT MIN(SALARY)
	FROM EMPLOYEE
);
-- 5. 노옹철 사원의 급여보다 초과하여 받는 직원의 사번, 이름, 부서명, 직급명, 급여 조회
-- 서브쿼리
SELECT SALARY
FROM EMPLOYEE
WHERE EMP_NAME = '노옹철'

SELECT EMP_NO, EMP_NAME, DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE SALARY > (
	SELECT SALARY
	FROM EMPLOYEE
	WHERE EMP_NAME = '노옹철'
);
-- 6. 부서별(부서가 없는 사람 포함) 급여의 합계 중 가장 큰 부서의 부서명, 급여 합계를 조회
SELECT MAX(SUM(SALARY))
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT * FROM EMPLOYEE;

SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
GROUP BY D.DEPT_TITLE
HAVING SUM(SALARY) = (
	SELECT MAX(SUM(SALARY))
	FROM EMPLOYEE
	GROUP BY DEPT_CODE
);

-- 7. 부서별 최고 급여를 받는 직원의 이름, 직급, 부서, 급여를 부서 순으로 정렬하여 조회 ✔✔


SELECT EMP_NAME, JOB_CODE, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY IN(
	SELECT MAX(SALARY)
	FROM EMPLOYEE
	GROUP BY DEPT_CODE
)
ORDER BY DEPT_CODE;

-- 8. 사수에 해당하는 직원에 대해 조회 사번, 이름, 부서명, 직급명, 구분(사수/사원)
SELECT * FROM EMPLOYEE;

SELECT MANAGER_ID
FROM EMPLOYEE
WHERE MANAGER_ID IS NOT NULL;

SELECT EMP_NO, EMP_NAME, DEPT_TITLE, JOB_NAME, '사수' 구분
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
WHERE E.EMP_ID IN (
	SELECT MANAGER_ID
	FROM EMPLOYEE
	WHERE MANAGER_ID IS NOT NULL
);

-- 9.대리 직급의 직원들 중에서 과장 직급의 최소 급여보다 많이 받는 직원의 사번, 이름, 직급명, 급여 조회
SELECT MIN(SALARY)
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE J.JOB_NAME = '과장'

SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE J.JOB_NAME = '대리' AND SALARY > (
	SELECT MIN(SALARY)
	FROM EMPLOYEE E
	JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
	WHERE J.JOB_NAME = '과장'
);

-- 10. 차장 직급의 급여 중 가장 큰 값보다 많이 받는 과장 직급의 직원 사번, 이름, 직급, 급여 조회
SELECT MAX(SALARY)
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE J.JOB_NAME = '차장';

SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE J.JOB_NAME = '과장' AND SALARY > (
	SELECT MAX(SALARY)
	FROM EMPLOYEE E
	JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
	WHERE J.JOB_NAME = '차장'
);
